### PR TITLE
Adding TR7 interpreter to the set

### PR DESCRIPTION
**Pull request by jobol**
Thank you a lot for your project.

I released v1.0.0 or TR7 yesterday 4th December 2022. In my opinion it a a valuable entry for your benchmark project. 

One of my friend is creating the ARCH package that will be soon available. I'm going to remove the [WIP] tag when it will be done. So no rush (as always 8D)

### CODE REVIEW

**Comment by jobol** [comment]
done! https://aur.archlinux.org/packages/tr7

**Comment by jobol** [comment]
ping

Is there a chance that my two PR get merged in some near future?

**Comment by jobol** [comment]
re ping ...

**Comment by jobol** [comment]
ping

**Comment by ecraven** [comment]
Sorry it took so long, merged.

**Comment by jobol** [comment]
Thank you for TR7. I'm very glad and about the time... I have no complain and I understand very well why. Regards

**Pull request merged**
