### PR TITLE
Ironscheme fixes

### PR DESCRIPTION
**Pull request by leppie**
https://github.com/ecraven/r7rs-benchmarks/issues/69

* Run on .NET rather than Mono
* Fix unbalanced parenthesis in `matrix.input`
* Update prelude to support more tests
* Update readme

Note: `HOME` is changed to the `pwd` in the bench script and that breaks the example script on my Linux. Not sure how to deal with it, except hard coding it.

### CODE REVIEW

**Comment by leppie** [comment]
Regarding changing `HOME` in the `bench` script.  https://github.com/ecraven/r7rs-benchmarks/blob/master/bench#L41

Is there any good reason to keep this? Nothing makes direct use of this and causes problems with any script called from `bench`. 

Unfortunately I dont have the means to run all the schemes to test if it would break anything.

**Comment by leppie** [comment]
All the benchmarks run now, iow they dont crash.

**Comment by ecraven** [comment]
> Regarding changing `HOME` in the `bench` script. https://github.com/ecraven/r7rs-benchmarks/blob/master/bench#L41
> 
> Is there any good reason to keep this? Nothing makes direct use of this and causes problems with any script called from `bench`.
> 
> Unfortunately I dont have the means to run all the schemes to test if it would break anything.

I'm not sure, I'll try to run the entire suite without it "soon", if it doesn't break anything, I'll remove it :D

**Comment by ecraven** [comment]
Thanks a lot for this!

**Pull request merged**
